### ISSUE TITLE
Stage "Deploy" fails if service mongodb is running on the target

### ISSUE THREAD

**Issue by gmacario** [hackafake/hackafake-backend#40]
See http://cc-vm1.solarma.it:9080/job/hackafake-backend/job/master/4/console

```
INFO: Deploying container to hackafake@staging.hackafake.com:/var/tmp/hackafake-backend-master
+ ssh -o StrictHostKeyChecking=no hackafake@staging.hackafake.com mkdir -p /var/tmp/hackafake-backend-master
+ rsync -avz --no-owner . hackafake@staging.hackafake.com:/var/tmp/hackafake-backend-master/
sending incremental file list
./
.git/
.git/FETCH_HEAD
.git/HEAD
.git/ORIG_HEAD
.git/config
.git/index
.git/logs/HEAD
.git/logs/refs/heads/
.git/logs/refs/heads/master
.git/logs/refs/remotes/origin/master
.git/objects/
.git/objects/06/
.git/objects/06/26a619e1953ff89ea1893666accc62dae4fb58
.git/objects/1e/
.git/objects/1e/6fac712d61c3c1e7e8b8b54a2094d0922a9490
.git/objects/3a/
.git/objects/3a/49cf94f3322287448c077ceb6dbda4380946da
.git/objects/b4/
.git/objects/b4/ca5de554f780a3b5f2d161c74153401533f911
.git/refs/heads/
.git/refs/heads/master
.git/refs/remotes/origin/
.git/refs/remotes/origin/master
bot/
bot/bot.py

sent 6,925 bytes  received 470 bytes  14,790.00 bytes/sec
total size is 93,967  speedup is 12.71
+ ssh -o StrictHostKeyChecking=no hackafake@staging.hackafake.com cd /var/tmp/hackafake-backend-master && git log -1 && git status && docker-compose build --pull && docker-compose up -d
commit 3a49cf94f3322287448c077ceb6dbda4380946da
Author: Gianpaolo Macario <gmacario@gmail.com>
Date:   Thu Aug 2 20:11:59 2018 +0200

    Post to http://api.hackafake.com:8080 (#39)
    
    Fix https://github.com/hackafake/hackafake-backend/issues/38
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	data/

nothing added to commit but untracked files present (use "git add" to track)
mongodb uses an image, skipping
Building server
[31380] Failed to execute script docker-compose
Traceback (most recent call last):
  File "site-packages/docker/utils/build.py", line 179, in create_archive
PermissionError: [Errno 13] Permission denied: '/var/tmp/hackafake-backend-master/data/journal/j._0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 127, in perform_command
  File "compose/cli/main.py", line 282, in build
  File "compose/project.py", line 373, in build
  File "compose/service.py", line 1047, in build
  File "site-packages/docker/api/build.py", line 154, in build
  File "site-packages/docker/utils/build.py", line 31, in tar
  File "site-packages/docker/utils/build.py", line 183, in create_archive
OSError: Can not read file in context: /var/tmp/hackafake-backend-master/data/journal/j._0
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
```

**Comment by gmacario** [comment]
WORKAROUND: Issue a `docker-compose down` on the target before deploying
(TBV: Maybe a `docker-compose stop` is enough?)

**Comment by gmacario** [comment]
After merging #41 the problem seems resolved

From 

```
...
.git/refs/remotes/origin/master

sent 6,255 bytes  received 464 bytes  13,438.00 bytes/sec
total size is 97,730  speedup is 14.55
+ ssh -o StrictHostKeyChecking=no hackafake@staging.hackafake.com cd /var/tmp/hackafake-backend-master && git log -1 && git status && docker-compose build --pull && docker-compose up -d
commit 18d2923c847d7011aa57e219868e052efe9720dd
Author: Gianpaolo Macario <gmacario@gmail.com>
Date:   Thu Aug 2 20:30:13 2018 +0200

    Create .dockerignore (#41)
    
    Should fix https://github.com/hackafake/hackafake-backend/issues/40
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	data/

nothing added to commit but untracked files present (use "git add" to track)
mongodb uses an image, skipping
Building server
Step 1/12 : FROM debian:latest
latest: Pulling from library/debian
Digest: sha256:f1f61086ea01a72b30c7287adee8c929e569853de03b7c462a8ac75e0d0224c4
Status: Image is up to date for debian:latest
 ---> 3bbb526d2608
...
Removing intermediate container e2d6dba8ed3a
 ---> c18fda900129
Successfully built c18fda900129
Successfully tagged hackafake-backend-master_server:latest
hackafake-backend-master_mongodb_1 is up-to-date
Recreating hackafake-backend-master_server_1 ... 
[1A[2K
Recreating hackafake-backend-master_server_1 ... [32mdone[0m
[1B[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

Finished: SUCCESS
```
