### ISSUE TITLE
ERROR in app: Exception on /challenge [GET]

### ISSUE THREAD

**Issue by gmacario** [hackafake/hackafake-backend#43]
In the attempt to rootcause #42 I encountered the following error while playing with the `/challenge` API inside Swagger interface

hackafake-backend manually deployed on `cc-vm1.solarma.it:/home/root/github/hackafake` with the following commands:

```shell
mkdir -p $HOME/github/hackafake
cd $HOME/github/hackafake
[ ! -e hackafake-backend ] && git clone https://github.com/hackafake/hackafake-backend
cd $HOME/github/hackafake/hackafake-backend
docker-compose pull && docker-compose build --pull && docker-compose up -d
```

Steps to reproduce:

1. Watch logs with `docker-compose logs -f server`
2. Browse <http://cc-vm1.solarma.it:8080>
   - Click "GET /challenge"
   - Click "Try it out!"

Results on docker-compose logs

```
server_1   | [2018-09-04 03:53:25,251] ERROR in app: Exception on /challenge [GET]
server_1   | Traceback (most recent call last):
server_1   |   File "/usr/lib/python3.5/random.py", line 262, in choice
server_1   |     i = self._randbelow(len(seq))
server_1   |   File "/usr/lib/python3.5/random.py", line 239, in _randbelow
server_1   |     r = getrandbits(k)          # 0 <= r < 2**k
server_1   | ValueError: number of bits must be greater than zero
server_1   |
server_1   | During handling of the above exception, another exception occurred:
server_1   |
server_1   | Traceback (most recent call last):
server_1   |   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
server_1   |     rv = self.dispatch_request()
server_1   |   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
server_1   |     return self.view_functions[rule.endpoint](**req.view_args)
server_1   |   File "/usr/local/lib/python3.5/dist-packages/flask_restplus/api.py", line 313, in wrapper
server_1   |     resp = resource(*args, **kwargs)
server_1   |   File "/usr/local/lib/python3.5/dist-packages/flask/views.py", line 84, in view
server_1   |     return self.dispatch_request(*args, **kwargs)
server_1   |   File "/usr/local/lib/python3.5/dist-packages/flask_restplus/resource.py", line 44, in dispatch_request
server_1   |     resp = meth(*args, **kwargs)
server_1   |   File "/usr/local/lib/python3.5/dist-packages/flask_restplus/marshalling.py", line 101, in wrapper
server_1   |     resp = f(*args, **kwargs)
server_1   |   File "./server/apis.py", line 68, in get
server_1   |     fake = random.choice(fakes)
server_1   |   File "/usr/lib/python3.5/random.py", line 264, in choice
server_1   |     raise IndexError('Cannot choose from an empty sequence')
server_1   | IndexError: Cannot choose from an empty sequence
```

**Comment by gmacario** [comment]
Notice that the mongodb database is currently empty.

Response after clicking "Try it out!" on http://cc-vm1.solarma.it:8080/#!/default/get_counter_resource

```
{
  "real": 0,
  "fake": 0
}
```

**Comment by gmacario** [comment]
Also, trying a POST on /fakenews returns respinse 500 (Internal Server Error)

**Comment by gmacario** [comment]
Next steps: Learn how to use logging inside Flask
Reference: http://flask.pocoo.org/docs/1.0/logging/
WIP: https://github.com/hackafake/hackafake-backend/pull/44
